### ISSUE TITLE
FB login not working Correctly

### ISSUE THREAD

**Issue by aravindiiitb** [Perseus14/VehicleTracking#5] opened 2016-04-23 21:19 UTC
Hi,
When a new user clicks on FB Login it's working fine. but when a return again and clicks login with fb then it is returning false.

**Comment by Perseus14** [comment] 2016-04-24 04:55
Can you attach some pics and elaborate on the steps to reproduce the bug?

**Comment by aravindiiitb** [comment] 2016-04-24 05:29
OK ..  Yesterday I have logged in with fb for the first time it worked good. When I loggedout of the account try to login again ... I'm getting this kind of error.
Pls look into this
![13054500_1698728817011382_758350831_o](https://cloud.githubusercontent.com/assets/9107251/14765724/63bc9d54-0a0b-11e6-9484-f41805c12040.png)

**Comment by Perseus14** [comment] 2016-04-24 06:49
I believe the issue was due to the change from development to production of the app. I have added the release key hash. Confirm if the error has been resolved by testing it in your phone as well as some other phone also.

**Closed as completed** 2016-04-24 11:18 UTC
